### PR TITLE
Add support for Laravel 7

### PR DESCRIPTION
**Pull request by maikelvanmaurik**

### CODE REVIEW

**Comment by aXent** [comment]
hi @cklmercer, thanks for this awesome package. Can you merge this in when you get the chance? I have a project in laravel 7 depending on this package as well.

**Comment by pmochine** [comment]
+++

**Comment by ABartelt** [comment]
I think PR#13 is also a good solution for laravel ^7.0 support

**Comment by cklmercer** [comment]
Sorry about the terrible delay! I wasn't receiving notifications for this repo, but I've since enabled notifications. Moving forward you should expect a better response time.

I've merged #13 so I'll be closing this PR.

**Pull request closed without merging**
