### PR TITLE
Support for Laravel 6

### PR DESCRIPTION
**Pull request by pktharindu**

### CODE REVIEW

**Comment by tharindu-abans** [comment]
@cklmercer can you please merge this and make a new release? Unable to upgrade to Laravel 6 without this.

**Review by cklmercer — APPROVED** [review]

**Comment by cklmercer** [comment]
thanks!

**Comment by tharindu-abans** [comment]
Awesome! Can you please make a new release too?

**Comment by cklmercer** [comment]
https://github.com/cklmercer/laravel-model-settings/releases/tag/1.3.1

**Pull request merged**
